### ISSUE TITLE
new changes break the software

### ISSUE THREAD

**Issue by derekparnell** [yuezk/GlobalProtect-openconnect#283]
Earlier today everything worked great, connection from ubuntu 22.04, and then I did an update and now things no longer work.  I checked and it looks like changes came through today and these are breaking changes.

The issue is that while it opens up the SSO for Microsoft, and I am able to enter my credentials, but then it shows what I assume is an error message, but it is extremely fast, and then it flips back to requiring me to enter my credentials.  Please help as this is causing my much trouble.

Or let me know if I can revert back to the older version, which I will try to do right now so that I can get back to work.

**Comment by yuezk** [comment]
Looks similar to #280. It has been fixed in 2.0.0-beta2, and published to PPA. Feel free to upgrade it or use the older version per the discussion in #280.

**Comment by pabrahamsson** [comment]
@yuezk, is 2.0.0-beta2 supposed to fix the connection issue (`Error: Invalid auth cookie, retrying can help`)?
I've tried beta1 and beta2, both give me the cookie error. It seems like beta2 fixed the issue with the user agent but that doesn't fix the connection issue for me.
I will try to downgrade to 1.4.9 but unfortunately the COPR repo only has the new version.

**Comment by yuezk** [comment]
@pabrahamsson Confirmed by other users, it has been fixed in 2.0.0-beta7. You could give it a try. Thanks.
