### ISSUE TITLE
Support setting HIP / csd-wrapper 

### ISSUE THREAD

**Issue by murph** [yuezk/GlobalProtect-openconnect#70]
Hey,

Openconnect supports "Host Integrity Protection" by calling an external program or wrapper script ([documentation](https://www.infradead.org/openconnect/hip.html)).

I can hack in support to GlobalProtect-openconnect my modifying the arguments that it invokes openconnect with:

```
--- a/GPService/gpservice.cpp
+++ b/GPService/gpservice.cpp
@@ -66,6 +66,7 @@ void GPService::connect(QString server, QString username, QString passwd)
     args << QCoreApplication::arguments().mid(1)
      << "--protocol=gp"
      << "-u" << username
+     << "--csd-wrapper=/home/murph/bin/hipreport.sh"    
      << "-C" << passwd
      << server;
```

I'd be happy to upstream this functionality (and make it configurable), but I don't see existing settings/configuration support in the application. Does the maintainer (or anyone really) has a preferred way to make something like this configurable (perhaps a settings file, or a command line option, or some GUI treatment?). I'm a competent programmer, but haven't worked in Qt5 enough to design the most natural setup.

**Comment by yuezk** [comment]
@murph Looks like you can use https://github.com/yuezk/GlobalProtect-openconnect/issues/21#issuecomment-745918352 as a workaround.

And I'm working on providing a setting to pass customized parameters easily.

**Comment by yuezk** [comment]
It should have been resolved in 1.3.0, as described in https://github.com/yuezk/GlobalProtect-openconnect#passing-the-custom-parameters-to-openconnect-cli

**Comment by wp4nuv** [comment]
I know this is closed, but I feel I must add: even when using 1.3.4 in Ubuntu and passing the `--csd-wrapper=<script>` into the optional params area (verified that script is executable), it still won't read it:
```
2021-11-08 07:46:26.506 INFO  [36406] [GPClient::onVPNLogAvailable@489] No MTU received. Calculated 1422 for ESP tunnel

2021-11-08 07:46:26.506 INFO  [36406] [GPClient::onVPNLogAvailable@489] POST https://corpportal.ticketnetwork.com/ssl-vpn/hipreportcheck.esp

2021-11-08 07:46:26.551 INFO  [36406] [GPClient::onVPNLogAvailable@489] Failed to exec HIP script /home/wp4nuv/hipreport.sh

2021-11-08 07:46:26.553 INFO  [36406] [GPClient::onVPNLogAvailable@489] HIP script '/home/wp4nuv/hipreport.sh' returned non-zero status: 1
Creating SSL connection failed
```
Does the csd-wrapper script need to be in a particular location?
